#应用名称
spring:
   application: 
      name: ccbp-core-bus
   datasource:
      driver-class-name=com: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/atmp?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      username: root
      password: zhangkaiMYSQL8!

#启动端口
server: 
   port: 8201
   servlet:
      context-path: /ccbp-core-bus

#注册中心
eureka:
   client:
      service-url:
         defaultZoon: http://localhost:8761/eureka

#mabatis映射文件
mybatis:
   mapper-locations: classpath:mapper/*.xml

